## Assignment Problem

In [1]:
import pandas as pd

Q1. Start by loading the IRIS dataset.

A. Display the following information
- First 10 rowa
- Shape & Data types
- Summary statistics (mean, std, min, max)

B. Select only those rows where:
- petal_lenght > 4.5
- species = "Iris-virginica"

C. Group by Species and compute:
- Average sepal_lenght
- Maximum petal_with
- Standard deviation

D. Create a new column: **"petal_ratio" = petal_lenght / petal_width**
- For each species, find the avrage petal_ratio.

In [2]:
# Load data
df = pd.read_csv("IRIS.csv")

# Print first 10 rows
df.head(10)

# Print Shape & Data types
df.shape
df.dtypes

# Summary statistics (mean, std, min, max)
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [3]:
# petal_lenght > 4.5
# species = "Iris-virginica"
cleand_data = df[ (df["petal_length"] > 4.5) & (df["species"] == "Iris-virginica")] 

cleand_data.head()

     sepal_length  sepal_width  petal_length  petal_width         species
100           6.3          3.3           6.0          2.5  Iris-virginica
101           5.8          2.7           5.1          1.9  Iris-virginica
102           7.1          3.0           5.9          2.1  Iris-virginica
103           6.3          2.9           5.6          1.8  Iris-virginica
104           6.5          3.0           5.8          2.2  Iris-virginica

In [4]:
# Average sepal_lenght
print(df.groupby("species")["sepal_length"].mean())
# Maximum petal_with
print(df.groupby("species")["petal_width"].max())
# Standard deviation
print(df.groupby("species")["sepal_width"].std())

species
Iris-setosa        5.006
Iris-versicolor    5.936
Iris-virginica     6.588
Name: sepal_length, dtype: float64
species
Iris-setosa        0.6
Iris-versicolor    1.8
Iris-virginica     2.5
Name: petal_width, dtype: float64
species
Iris-setosa        0.381024
Iris-versicolor    0.313798
Iris-virginica     0.322497
Name: sepal_width, dtype: float64

In [5]:
# For each species, find the avrage petal_ratio.
df['petal_ratio'] = df['petal_length'] / df['petal_width']
print(df.groupby('species')['petal_ratio'].mean())

species
Iris-setosa        7.078000
Iris-versicolor    3.242837
Iris-virginica     2.780662
Name: petal_ratio, dtype: float64

In [6]:
df.head()

,sepal_length,sepal_width,petal_length,petal_width,species,petal_ratio
0,5.1,3.5,1.4,0.2,Iris-setosa,7.0
1,4.9,3.0,1.4,0.2,Iris-setosa,7.0
2,4.7,3.2,1.3,0.2,Iris-setosa,6.5
3,4.6,3.1,1.5,0.2,Iris-setosa,7.5
4,5.0,3.6,1.4,0.2,Iris-setosa,7.0

Q2. Start by loading the **TITANIC** dataset.

A. Display only columns: Name, Sex, Age, Fare, Survived

B. Select passengers who:
- Are female
- Fare > 30

C. Group by Pclass and compute:
- Survival rate
- Average Fare
- Average Age

In [11]:
# Load data
df = pd.read_csv("Titanic-Dataset.csv")
# Step A
df_selected = df[['Name', 'Sex', 'Age', 'Fare', 'Survived']]
print(df_selected)
# Step B
filterd_df = df_selected[(df_selected["Sex"] == "female") & (df_selected["Fare"] > 30)]
print(filterd_df)

# Step C
print("Survival Rate:\n", df.groupby('Pclass')['Survived'].mean())
print("Average Fare:\n", df.groupby('Pclass')['Fare'].mean())
print("Average Age:\n", df.groupby('Pclass')['Age'].mean())

                                                  Name     Sex   Age     Fare  \
0                              Braund, Mr. Owen Harris    male  22.0   7.2500
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0  71.2833
2                               Heikkinen, Miss. Laina  female  26.0   7.9250
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0  53.1000
4                             Allen, Mr. William Henry    male  35.0   8.0500
..                                                 ...     ...   ...      ...
886                              Montvila, Rev. Juozas    male  27.0  13.0000
887                       Graham, Miss. Margaret Edith  female  19.0  30.0000
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN  23.4500
889                              Behr, Mr. Karl Howell    male  26.0  30.0000
890                                Dooley, Mr. Patrick    male  32.0   7.7500

     Survived
0           0
1           1
2           1
3           1
4           0
..        ...
886         0
887         1
888         0
889         1
890         0

[891 rows x 5 columns]
                                                  Name     Sex   Age  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0
25   Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...  female  38.0
31      Spencer, Mrs. William Augustus (Marie Eugenie)  female   NaN
..                                                 ...     ...   ...
853                          Lines, Miss. Mary Conover  female  16.0
856         Wick, Mrs. George Dennick (Mary Hitchcock)  female  45.0
863                  Sage, Miss. Dorothy Edith "Dolly"  female   NaN
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  47.0
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0

         Fare  Survived
1     71.2833         1
3     53.1000         1
9     30.0708         1
25    31.3875         1
31   146.5208         1
..        ...       ...
853   39.4000         1
856  164.8667         1
863   69.5500         0
871   52.5542         1
879   83.1583         1

[113 rows x 5 columns]
Survival Rate:
 Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64
Average Fare:
 Pclass
1    84.154687
2    20.662183
3    13.675550
Name: Fare, dtype: float64
Average Age:
 Pclass
1    38.233441
2    29.877630
3    25.140620
Name: Age, dtype: float64