In [27]:
import requests
import pandas as pd

In [28]:
URL = "https://stephen-king-api.onrender.com/api/books"
res = requests.get(URL)

In [29]:
json_data = res.json()

In [30]:
df = pd.json_normalize(json_data["data"])
df = df[['id', 'Title', 'Year', 'ISBN']]

In [31]:
df

    id            Title  Year                  ISBN
0    1           Carrie  1974     978-0-385-08695-0
1    2      Salem's Lot  1975     978-0-385-00751-1
2    3      The Shining  1977     978-0-385-12167-5
3    4             Rage  1977     978-0-451-07645-8
4    5        The Stand  1978     978-0-385-12168-2
..  ..              ...   ...                   ...
59  60        Elevation  2018     978-1-98210-231-9
60  61    The Institute  2019     978-1-98211-056-7
61  62            Later  2021     978-1-78909-649-1
62  63    Billy Summers  2021     978-1-982-17361-6
63  72  The Roopak Zone  1979  978-0-670-26069697-5

[64 rows x 4 columns]

In [40]:
URL = "https://api.artic.edu/api/v1/artworks/129884"
api_request = requests.get(URL)

In [41]:
json_data1 = api_request.json()

In [42]:
df = pd.json_normalize(json_data1["data"])

In [43]:
df

,id,api_model,api_link,is_boosted,title,alt_titles,main_reference_number,has_not_been_viewed_much,boost_rank,date_start,...,timestamp,thumbnail.lqip,thumbnail.width,thumbnail.height,thumbnail.alt_text,color.h,color.l,color.s,color.percentage,color.population
0,129884,artworks,https://api.artic.edu/api/v1/artworks/129884,True,Starry Night and the Astronauts,None,1994.36,False,1,1972,...,2026-07-06T11:29:56-05:00,"data:image/gif;base64,R0lGODlhBAAFAPQAABw/Zhg/...",5376,6112,Abstract painting composed of small vertical d...,45,49,94,0.003595,29

In [54]:
URL = "https://www.scrapethissite.com/pages/simple/"
res = requests.get(URL)

In [56]:
if res.status_code == 200:
    print(res.headers)

with open("scraped_data/data1.html", "wb") as f:
    f.write(res.content)

{'Date': 'Mon, 06 Jul 2026 17:37:18 GMT', 'Content-Type': 'text/html; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Nel': '{"report_to":"heroku-nel","response_headers":["Via"],"max_age":3600,"success_fraction":0.01,"failure_fraction":0.1}', 'Report-To': '{"group":"heroku-nel","endpoints":[{"url":"https://nel.heroku.com/reports?s=kUPDRe4fSOQ3TmxCprWuuWBQxf2KxM0r5ExtFl3JP9A%3D\\u0026sid=67ff5de4-ad2b-4112-9289-cf96be89efed\\u0026ts=1783359438"}],"max_age":3600}', 'Reporting-Endpoints': 'heroku-nel="https://nel.heroku.com/reports?s=kUPDRe4fSOQ3TmxCprWuuWBQxf2KxM0r5ExtFl3JP9A%3D&sid=67ff5de4-ad2b-4112-9289-cf96be89efed&ts=1783359438"', 'Server': 'cloudflare', 'Via': '1.1 heroku-router', 'Cf-Cache-Status': 'DYNAMIC', 'Content-Encoding': 'gzip', 'CF-RAY': 'a1706067ec9c5f48-SIN', 'alt-svc': 'h3=":443"; ma=86400'}

In [57]:
# BeautifulSoup

from bs4 import BeautifulSoup

with open("scraped_data/data1.html", "r") as f:
    html_content = f.read()

soup = BeautifulSoup(html_content, "lxml")

In [59]:
all_h3 = soup.find_all("h3")

all_countries = []

for h3 in all_h3:
    name = h3.get_text(strip=True)
    # print(h3.find_parent("div")["class"])

    population = h3.find_next("div").select("span.country-population")[0].get_text(strip=True)
    # print(h3.find_next("div").select_one("span.country-population").get_text(strip=True))

    all_countries.append([name, population])

In [62]:
import pandas as pd
df = pd.DataFrame(all_countries, columns=["Name", "Population"])

In [64]:
df.to_csv("cleaned_data/data.csv", index=False)